# 1. Create a null vector of size 10 but the fifth value which is 1

In [1]:
import numpy as np
vector = np.zeros(10)
vector[4]=1
print(vector)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


# 2. Create a vector with values ranging from 10 to 49.

In [2]:
import numpy as np

vec=np.arange(10,50)
print(vec)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


# 3. Create a 3x3 matrix with values ranging from 0 to 8

In [3]:
vector=np.arange(0,9)
matrix=vector.reshape(3,3)
print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


# 4. Find indices of non-zero elements from [1,2,0,0,4,0]

In [5]:
arr=[1,2,0,0,4,0]
indices=np.nonzero(arr)
print(indices)

(array([0, 1, 4], dtype=int64),)


# 5. Create a 10x10 array with random values and find the minimum and maximum values.

In [7]:
arr_5=np.random.random((10,10))
max_value=arr_5.max()
min_value=arr_5.min()
print(f"maximum Value: {max_value} ")
print(f"minimum Value: {min_value} ")

maximum Value: 0.9864234624431226 
minimum Value: 0.019614090839859766 


# 6. Create a random vector of size 30 and find the mean value.

In [11]:
vector=np.random.random(30)
mean=vector.mean()
print(f"Mean Value : {mean}")

Mean Value : 0.5028157522893014
